# L1,L2计算

## “曼哈顿距离”(L1范数)
https://blog.csdn.net/dear_zhoubi/article/details/97391925

## 
欧几里得距离 == 欧几里得范数 == L2范数 == L2距离

Euclidean distance == Euclidean norm == L2 norm == L2 distance
https://blog.csdn.net/weixin_43708622/article/details/111143389

In [3]:
import numpy as np

# 向量
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

# L1
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
 
op3=np.sum(np.abs(vector1-vector2))
op4=np.linalg.norm(vector1-vector2,ord=1)
print(op3)
#输出
#9
#9.0


# L2
op1=np.sqrt(np.sum(np.square(vector1-vector2)))
op2=np.linalg.norm(vector1-vector2)
print(op1)
print(op2)
#输出:
#5.19615242271
#5.19615242271

9
5.196152422706632
5.196152422706632


## numpy 三个点的使用[...]  多维切片
https://blog.csdn.net/weixin_33752045/article/details/94051330
https://www.cnblogs.com/double-t/p/11067950.html


numpy数组中冒号[:,:,0]与[...,0]的区别： https://blog.csdn.net/weixin_37552816/article/details/89285235

In [13]:
import numpy as np 
a = np.array([  [1,2,3,4,5],
                [6,7,8,9,10],
                [1,2,3,4,5],
                [6,7,8,9,10]
             ]) # 
print(a.shape) # 4行5列
print(a[:,2], a[:,2].shape) # 注意区别
print(a[...,2], a[...,2].shape) #表示遍历每行，2表示索引为2的所在列

(4, 5)
[3 8 3 8] (4,)
[3 8 3 8] (4,)


In [7]:

a[...,:2]#表示遍历每行，:2表示索引为<2的0，1所在的列

array([[1, 2],
       [6, 7],
       [1, 2],
       [6, 7]])

In [15]:
a[...,::2]#表示遍历每行，2表示步长，选取多索引为0，2，4所在的列

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [ 1,  3,  5],
       [ 6,  8, 10]])

In [21]:

print(a[None,...])#相当于插入维度，也想当于reshape(a,[1,4,4])
a = a.reshape(1,4,5)
print(a)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [ 1  2  3  4  5]
   [ 6  7  8  9 10]]]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


In [24]:
import numpy as np
out = np.array([[[1,2],[2,3],[3,4]]])
print(out.shape)
out

(1, 3, 2)


array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [27]:
print(out[:,0]) # 等同于out[:,0,:]
print(out[...,0])
print(out[...,1])

[[1 2]]
[[1 2 3]]
[[2 3 4]]


### 三个点和冒号两个点的区别
https://blog.csdn.net/w666665/article/details/117478602

In [30]:
import numpy as np

a = np.arange(8).reshape((2, 2, 2))
print(a)
print("=========================")
print(a[0, :])
print(a[0, ...])
print(a[:, 0]) # 等同于a[:,0,:]
print(a[..., 0]) # 等同于a[:,:,0]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[0 1]
 [4 5]]
[[0 2]
 [4 6]] [[0 2]
 [4 6]]
