# 总结


https://www.yuque.com/huangzhongqing/efgg5d/kqgvck

1 向量：一维数组

2 矩阵：二维数组

3 三维及更高维数组





## 1 向量 （一维数组）

In [40]:
import numpy as np
# np.array([1,2,3],dtype=np.float64)
# # 向量
# np.zeros(3)
# np.ones(3)
# np.empty(3)
# np.full(3, 7.) # 3个7


# 初始化
a = np.array([1,2,3],dtype=np.float64)
b= np.array((2,3))
# print(a)
# print(b.shape)
# 所有用常量填充创建的数组的函数都有一个_like对应项，来创建相同类型的常数数组：
# a= np.array([1,2,3])
# b = np.ones_like(a)
# print(a,b)

# linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
np.linspace(0, 1,10)

# 布尔运算
x = np.arange(6)
print(x>3)
print(x[x>3])



[False False False False  True  True]
[4 5]


In [36]:
np.random.rand(10,2)# “0~1”均匀分布的随机样本值。随机样本取值范围是[0,1)，不包括1。
np.random.randn(10,2)# 标准只正态分布 由 np.random.randn()函数所产生的随机样本基本上取值主要在-1.96~+1.96之

array([[ 0.23776425, -1.40777031],
       [-0.46054247,  0.49819585],
       [ 1.0328728 , -0.47308017],
       [-1.86349063, -0.10585146],
       [ 0.22240327,  1.95244091],
       [-0.44429165,  0.66132506],
       [ 0.39564736,  0.14678605],
       [ 0.14878296, -0.625336  ],
       [-0.40019462,  1.16749128],
       [-0.52960361, -0.94622215]])

## 2 矩阵 （二维数组）

In [49]:
np.array([[1,2,3],
                    [4,5,6]])
np.zeros((3,2))
np.ones((3,2))
np.full((3,2), 7)
np.empty((3,2))
np.eye(3) #等价于np.eye((3,3))


# 随机
np.random.rand(3,2) # 高斯

array([[0.44388105, 0.01806068],
       [0.45471891, 0.56904175],
       [0.58314025, 0.97960235]])

## 3 三维与更高维数组

In [52]:
np.arange(1,9).reshape(2,2,2)
# 随机
np.random.rand(3,2, 3) # 高斯

array([[[0.05462599, 0.15195533, 0.34710855],
        [0.59272743, 0.72997102, 0.41632189]],

       [[0.30732203, 0.66043887, 0.63522177],
        [0.49241602, 0.30406842, 0.86291985]],

       [[0.95657327, 0.63323212, 0.88498331],
        [0.43204398, 0.07614296, 0.75861439]]])