In [1]:
import numpy as np

In [2]:
A = np.arange(2,14).reshape((3,4))

`np.argmin(A) # 最小值的索引`
`np.argmax(A) # 最小值的索引`

In [3]:
print(A)
print(np.argmin(A)) # 最小值的索引)
print(np.argmax(A)) # 最小值的索引

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11


* np.mean() 均值
* np.median()中位数
* np.cumsum()累加
* np.diff()累差

In [16]:
print(np.mean(A))
print(A.mean())
print(np.median(A))
print(np.cumsum(A))
print(np.diff(A))


7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


 * np.nonzero() 显示几行几列

In [18]:
print(np.nonzero(A))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


* 排序sort()
* 转置 transpose() OR  A.T 行变列，列变行

In [23]:
print(np.sort(A))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


In [29]:
print(np.transpose(A))
print(A.T)

[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


* clip(A,5,9)  小于5的数全部变成5，大于9的数全部变成9

In [27]:
np.clip(A,5,9)


array([[5, 5, 5, 5],
       [6, 7, 8, 9],
       [9, 9, 9, 9]])

In [28]:
A.clip(5,9)

array([[5, 5, 5, 5],
       [6, 7, 8, 9],
       [9, 9, 9, 9]])



* axis = 0行计算 
* axis = 1列计算
* axis=1为横向，axis=0为纵向，而不是行和列

* axis的取值不限于0/1/2，还可以拓展到高维数组。一维数组时axis=0，二维数组时axis=0，1，维数越高，则axis可取的值越大

好文章：https://blog.csdn.net/sky_kkk/article/details/79725646

In [41]:
print(A)
np.sum(A,axis=0)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


array([18, 21, 24, 27])

In [42]:
np.sum(A,axis=1)

array([14, 30, 46])

首先定义一个2x3x4的三维数组a：

In [43]:
a = [[[1,2 ,3 ,4 ],
      [5,6 ,7 ,8 ],
      [9,10,11,12]],
     [[13,14,15,16],
      [17,18,19,20],
      [21,22,23,24]]]

（2）用numpy中的sum函数对a求和，先输入axis=0：

In [45]:
sum_0 = np.sum(a,axis = 0)
print(sum_0)
# 输出结果是一个3x4的数组

[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]


（3）再用sum函数对a求和，输入axis=1：

In [47]:
sum_1 = np.sum(a,axis = 1)
print(sum_1)

[[15 18 21 24]
 [51 54 57 60]]


（4）最后用sum函数对a求和，输入axis=2：

In [48]:
sum_2 = np.sum(a,axis = 2)
print(sum_2)

[[10 26 42]
 [58 74 90]]
