In [1]:
import numpy as np

In [2]:
A = np.arange(3,15)
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
A = np.arange(3,15).reshape((3,4))
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [12]:
print(A[2])
print(A[2][0])
print(A[2,0])
print(A[2,:])
print(A[2,1:3])

[11 12 13 14]
11
11
[11 12 13 14]
[12 13]


* for循环

In [13]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


* 列迭代

In [15]:
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


* A.flatten() 变成一行的序列
* A.flat 迭代器

In [17]:
print(A.flatten())

for item in A.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
