## 总结
Python中numpy数组的合并有很多方法，如

np.append()
np.concatenate()
np.stack()
np.hstack()
np.vstack()

In [2]:
import numpy as np

In [3]:
A =np.array([1,1,1])
B =np.array([2,2,2])
print('A:',A)
C = np.vstack((A,B)) # 
D = np.hstack((A,B)) #

A: [1 1 1]


## 1 【维度不变】拼接np.stack, np.vstack(0维), np.hstack(1维/最后一维列)
* np.vstack((A,B)) 上下合并
* np.hstack((A,B)) z左右合并


### np.stack() 需要琢磨 在某个维度对应彼此合并
axis=0是把原来的元素按照横轴的方式排列，axis=1是把原先元素按照纵轴排列

In [12]:

import numpy as np
 
# stack()是按照不同轴的堆叠方式重新堆叠数组
 
a=np.array([[1,2,3],
            [4,5,6]])
 
np.stack(a,axis=0)
# array([[1, 2, 3],
#       [4, 5, 6]])
 
np.stack(a,axis=1)
# array([[1, 4],
#       [2, 5],
#       [3, 6]])
 
#可以看出axis=0是把原来的元素按照横轴的方式排列，axis=1是把原先元素按照纵轴排列


array([[1, 4],
       [2, 5],
       [3, 6]])

###  np.vstack(0维), np.hstack(1维/最后一维列)

In [6]:
a=[1,2,3]
 
b=[4,5,6]
 
print(np.hstack((a,b)))
#array([1, 2, 3, 4, 5, 6])
 
print(np.vstack((a,b)))
#array([[1, 2, 3],
#       [4, 5, 6]])


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


###  np.concatenate((A, B), axis=0) 能够一次完成多个数组的拼接。  类似torch.cat  (Pytorch_API/tensor数据处理torch_with_numpy.ipynb)

* 合并多个，np.concatenate((A,B,B,A), axis=0)


根据官方的说法，
* 1表示横轴，方向从左到右；0表示纵轴，方向从上到下。
* 当axis=1时，数组的变化是横向的，而体现出来的是列的增加或者减少。



In [30]:
a=np.array([[1,2,3],
            [1,2,3]])
b=np.array([[11,22,33],
            [11,22,33]])

print(np.concatenate((a,b) ,axis=0))
print(np.concatenate((a,b) ,axis=-1)) #！！！！！！！！！！！！！！！！！！

[[ 1  2  3]
 [ 1  2  3]
 [11 22 33]
 [11 22 33]]
[[ 1  2  3 11 22 33]
 [ 1  2  3 11 22 33]]


## 增加维度
https://blog.csdn.net/weixin_39059031/article/details/108037744

### 1 np.newaxis：关键字，使用索引的语法给数组添加维度
### 2 np.expand_dims(arr, axis)：方法，和np.newaxis实现一样的功能，给arr在axis位置添加维度
### 3 np.reshape(a, newshape)：方法，给一个维度设置为1完成升维



a[:,np.newaxis]
* 横向数列变为纵向数列 A.T不行
a[np.newaxas,:]横向加了一个维度
a[:,np.newaxis]纵向加了一个维度

In [20]:
# ### 1 np.newaxis：关键字，使用索引的语法给数组添加维度

a = np.arange(6).reshape(2,3)
print(a.shape)

print(a[np.newaxis,:].shape) #前面增加一维度 (1,4,3)
print(a[:,np.newaxis].shape) # 中间增加1维度
print(a[:,:,np.newaxis].shape) # 最后增加1维度

(2, 3)
(1, 2, 3)
(2, 1, 3)
(2, 3, 1)


In [24]:
### 2 np.expand_dims(arr, axis)：方法，和np.newaxis实现一样的功能，给arr在axis位置添加维度


a = np.arange(6).reshape(2,3)
print(np.expand_dims(a, axis=0).shape)

(1, 2, 3)


In [25]:
### 3 np.reshape(a, newshape)：方法，给一个维度设置为1完成升维


a = np.arange(6).reshape(2,3)
print(a.reshape(-1,2,3).shape) # 开头增加一个维度

(1, 2, 3)


In [ ]:
## TODO 