In [2]:
import numpy as np

In [22]:
A =np.array([1,1,1])
B =np.array([2,2,2])
print('A:',A)
C = np.vstack((A,B)) # 
D = np.hstack((A,B)) #

A: [1 1 1]


* np.vstack((A,B) 上下合并
* np.hstack((A,B)) z左右合并

In [13]:
print('C:',np.vstack((A,B)))
print('D:',np.hstack((A,B)))
print(A.shape,C.shape,D.shape)

C: [[1 1 1]
 [2 2 2]]
D: [1 1 1 2 2 2]
(3,) (2, 3) (6,)


* 横向数列变为纵向数列 A.T不行
A[np.newaxis,:]横向加了一个维度
A[:,np.newaxis]纵向加了一个维度

In [16]:
print(A[np.newaxis,:])
print(A[np.newaxis,:].shape)
print(A[:,np.newaxis])

[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]


* 合并多个，np.concatenate((A,B,B,A), axis=0)


根据官方的说法，
* 1表示横轴，方向从左到右；0表示纵轴，方向从上到下。
* 当axis=1时，数组的变化是横向的，而体现出来的是列的增加或者减少。



In [21]:
A =np.array([1,1,1])[:, np.newaxis]
B =np.array([2,2,2])[:, np.newaxis]
C =np.concatenate((A,B,B,A),axis=0) #纵向合并
print(C)
C =np.concatenate((A,B,B,A), axis=1) #横向合并
print(C)


[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
