### 28numpy的copy和deepcopy

In [1]:
import numpy as np

In [2]:
a = np.arange(4)
print(a)
b=a
c=a
d=b

[0 1 2 3]


In [7]:
a[0] =11
print(a)
print(b)
print(b is a) # b是a吗

d[2:4] = [22,33]
print(a,d)

[11  1  2  3]
[11  1  2  3]
True
[11  1 22 33] [11  1 22 33]


* b = a.copy() # deep copy

In [16]:
a = np.arraay
b = a.copy() # deep copy
print(a,b)
a[3] =  55
print("a,b值不一样：",a,b)

[11  1 22 55] [11  1 22 55]
a,b值不一样： [11  1 22 55] [11  1 22 55]
